In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
a = np.zeros(3)
print a

[ 0.  0.  0.]


In [7]:
b = np.ones((2,3))
print b

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [9]:
c = np.random.randint(1,10,(2,3,4))
# click + Shift + Tab for documentation
print c

[[[5 3 8 1]
  [3 2 2 3]
  [9 5 6 5]]

 [[6 9 7 8]
  [2 7 5 8]
  [8 2 8 5]]]


In [12]:
d = np.arange(0,11,1)
print d
d

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[5, 3, 8, 1],
         [3, 2, 2, 3],
         [9, 5, 6, 5]],
 
        [[6, 9, 7, 8],
         [2, 7, 5, 8],
         [8, 2, 8, 5]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [15]:
a = np.array([20,30,40,50])
b = np.arange(4)
a

array([20, 30, 40, 50])

In [16]:
b

array([0, 1, 2, 3])

In [18]:
c = a-b
c

array([20, 29, 38, 47])

In [19]:
b ** 2 

array([0, 1, 4, 9])

In [21]:
a  = np.arange(10) ** 2 
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
a[2:5]
# python no exlusive

array([ 4,  9, 16])

In [24]:
b = np.random.randint(1,100,(4,4))
b

array([[80, 16, 25, 50],
       [77, 66, 28, 41],
       [78, 22, 43, 11],
       [21, 20, 98, 35]])

In [26]:
b[0:3,1],b[:,1]

(array([16, 66, 22]), array([16, 66, 22, 20]))